# Set your configuration here!

users = [
    "username",
    "guest",
]
# List of users to include in blocking.
# Users not listed here remain unaffected.

allowed_times = [
    "05:00 - 20:00", 
]
# Allowed usage time ranges during the day. You can specify multiple ranges.
# Comment it out to disable time range based blocking.
# Are you productive after 8pm?

timezone = "Europe/London"
# Your timezone. 
# For a full list of available timezones, run the script: ./screentimer.nu list-timezones

extra_time = "10min"
# Maximum extra allowed usage time per day, outside of all other limits.
# Comment it out to disable extra time.

total_time = "6hr"
# Total allowed screen usage time per day.
# Once this total is exceeded, further usage is blocked.
# Comment it out to disable total time counting.
# Are you productive after 6 hours, or is it better for you to take a walk instead?

day_start = "4am"
# The time of day at which usage counters reset.
# It's recommended to keep this unchanged.

offline_time = "15min"
# Maximum allowed offline usage time per day (usage without connectivity).
# Comment it out to completely disable offline usage.
# It's recommended to keep this unchanged.

after_boot_allowed = "2min"
# Duration after system boot during which all limits are disabled.
# Useful for connecting to Wi-Fi, logging in to institution networks, etc.
# It's highly recommended to keep this unchanged.